export const colors = {
  "bg-secondary": "#222222",
  "bg-primary": "#111111",
  "bg-primary-active": "#333333",
  "accent-primary": "#ee2b65",
  "accent-primary-active": "#FFFFFF",
  "icons-primary": "#ee2b65",
  "icons-secondary": "#AAAAAA",
  "borders-secondary": "#AAAAAA",
  "borders-strong": "#FFFFFF",
  "light-shadow": "#111111",
  warning: "#CC3333",
  // Continuing the dark palette
  "txt-primary": "#ee2c70",
  "txt-secondary": "#ee2c70",
  "txt-secondary-invert": "#333333",
  "txt-placeholder": "#666666",
  "txt-warning": "#ee2c70",
  "txt-error": "#FF4500",
  "txt-info": "#5BC0DE",
  "accent-primary-hover": "#ee2c70",
  "accent-primary-disabled": "#888888",
  "accent-secondary-disabled": "#444444",
  "accent-stateless": "#ee2c70",
  "accent-stateless_0_4_opacity": "rgba(221,  221,  221,  0.4)",
  accent_0_5_opacity: "#DDDDDD0D",
  accent_1_2_opacity: "#DDDDdd1f",
  accent_1_8_opacity: "#DDDDDD2E",
  accent_2_8_opacity: "#DDDDDD47",
  accent_4_0_opacity: "#DDDDDD66",
  "bg-grey": "#333333",
  "bg-stateless": "#111111",
  "bg-active": "#2B2B2B",
  "bg-base-light": "#222222",
  "bg-base-medium": "#1F1F1F",
  "bg-primary-light": "#111111",
  "bg-primary-hover": "#1A1A1A",
  "bg-primary-stateless": "#1A1A1A",
  "bg-hover": "#1A1A1A",
  "bg-green": "#004400",
  "bg-green-medium": "#006600",
  "bg-blue": "#000044",
  "bg-red": "#440000",
  "bg-red-light": "#660000",
  "background-red-medium": "#880000",
  "bg-orange": "#442200",
  "bg-tooltip": "#1A1A1A",
  "icon-primary": "#ee2c70",
  "icons-primary-opacity-0-6": "rgba(255,  177,  0,  0.600)",
  "icons-placeholder": "#666666",
  "icons-invert": "#FFFFFF",
  "icons-muted": "#999999",
  "icons-primary-hover": "#ee2c70",
  "icons-secondary-hover": "#ee2c70",
  "btn-primary-text": "#FFFFFF",
  "btn-primary-text-0-6": "rgba(255,  255,  255,  0.6)",
  "btn-primary-text-0-4": "rgba(255,  255,  255,  0.4)",
  "btn-disabled-text": "#666666",
  "btn-secondary-text": "#FFFFFF",
  "link-primary": "#ee2c70",
  "link-stateless": "#ee2c70",
  "link-hover": "#ee2c70",
  "link-active": "#FFFFFF",
  "link-pressed": "#ee2c70",
  "link-muted": "#999999",
  "borders-primary": "#CCCCCC",
  "borders-primary-hover": "#DDDDDD",
  "borders-invert": "#000000",
  "border-hover-bottom": "#DDDDDD0.18",
  "border-active-bottom": "#FFFFFF",
  "border-primary-stateless": "#CCCCCC",
  "borders-disabled": "#88888866",
  "borders-button": "#AAAAAA",
  "borders-item": "#333333",
  "borders-base-light": "#2B2B2B",
  "borders-base-medium": "#1F1F1F",
  "borders-green": "#00440022",
  "borders-green-medium": "#00440040",
  "borders-red": "#44000040",
  "active-secondary": "#FFFFFF",
  "active-secondary-hover": "#DDDDDD0.05",
};

export const translations = {
  name: "Nome",
  save: "Salvar",
  saveAs: "Salvar como",
  back: "Voltar",
  loading: "Carregando...",
  resetOperations: "Redefinir/excluir todas as operações",
  changesLoseWarningHint:
    'Se pressionar o botão "redefinir", suas alterações serão perdidas. Deseja continuar?',
  discardChangesWarningHint:
    "Se fechar a janela modal, suas últimas alterações não serão salvas.",
  cancel: "Cancelar",
  apply: "Aplicar",
  warning: "Aviso",
  confirm: "Confirmar",
  discardChanges: "Descartar alterações",
  undoTitle: "Desfazer última operação",
  redoTitle: "Refazer última operação",
  showImageTitle: "Mostrar imagem original",
  zoomInTitle: "Aumentar zoom",
  zoomOutTitle: "Diminuir zoom",
  toggleZoomMenuTitle: "Alternar menu de zoom",
  adjustTab: "Ajustar",
  finetuneTab: "Ajustes",
  filtersTab: "Filtros",
  watermarkTab: "Marca d'água",
  annotateTabLabel: "Anotar",
  resize: "Tamanho",
  resizeTab: "Tamanho",
  imageName: "Nome da imagem",
  invalidImageError: "Imagem fornecida inválida.",
  uploadImageError: "Erro ao enviar a imagem.",
  areNotImages: "não são imagens",
  isNotImage: "não é uma imagem",
  toBeUploaded: "para ser enviada",
  cropTool: "Cortar",
  original: "Original",
  custom: "Personalizado",
  square: "Quadrado",
  landscape: "Paisagem",
  portrait: "Retrato",
  ellipse: "Elipse",
  classicTv: "TV clássica",
  cinemascope: "Cinemascope",
  arrowTool: "Seta",
  blurTool: "Desfoque",
  brightnessTool: "Brilho",
  contrastTool: "Contraste",
  ellipseTool: "Elipse",
  unFlipX: "Desvirar X",
  flipX: "Virar X",
  unFlipY: "Desvirar Y",
  flipY: "Virar Y",
  hsvTool: "HSV",
  hue: "Matiz",
  brightness: "Brilho",
  saturation: "Saturação",
  value: "Valor",
  imageTool: "Imagem",
  importing: "Importando...",
  addImage: "+ Adicionar imagem",
  uploadImage: "Enviar imagem",
  fromGallery: "Da galeria",
  lineTool: "Linha",
  penTool: "Caneta",
  polygonTool: "Polígono",
  sides: "Lados",
  rectangleTool: "Retângulo",
  cornerRadius: "Raio da borda",
  resizeWidthTitle: "Largura em pixels",
  resizeHeightTitle: "Altura em pixels",
  toggleRatioLockTitle: "Alternar bloqueio de proporção",
  resetSize: "Redefinir para o tamanho original da imagem",
  rotateTool: "Girar",
  textTool: "Texto",
  textSpacings: "Espaçamentos de texto",
  textAlignment: "Alinhamento de texto",
  fontFamily: "Família da fonte",
  size: "Tamanho",
  letterSpacing: "Espaçamento entre letras",
  lineHeight: "Altura da linha",
  warmthTool: "Calor",
  addWatermark: "+ Adicionar marca d'água",
  addTextWatermark: "+ Adicionar marca d'água de texto",
  addWatermarkTitle: "Escolher o tipo de marca d'água",
  uploadWatermark: "Enviar marca d'água",
  addWatermarkAsText: "Adicionar como texto",
  padding: "Preenchimento",
  paddings: "Preenchimentos",
  shadow: "Sombra",
  horizontal: "Horizontal",
  vertical: "Vertical",
  blur: "Desfoque",
  opacity: "Opacidade",
  transparency: "Transparência",
  position: "Posição",
  stroke: "Traço",
  saveAsModalTitle: "Salvar como",
  extension: "Extensão",
  format: "Formato",
  nameIsRequired: "Nome é obrigatório.",
  quality: "Qualidade",
  imageDimensionsHoverTitle: "Tamanho da imagem salva (largura x altura)",
  cropSizeLowerThanResizedWarning:
    "Nota: a área de recorte selecionada é menor que o redimensionamento aplicado, o que pode causar uma diminuição na qualidade",
  actualSize: "Tamanho real (100%)",
  fitSize: "Ajustar tamanho",
  addImageTitle: "Selecionar imagem para adicionar...",
  mutualizedFailedToLoadImg: "Falha ao carregar a imagem.",
  tabsMenu: "Menu",
  download: "Baixar",
  width: "Largura",
  height: "Altura",
  plus: "+",
  cropItemNoEffect: "Nenhuma prévia disponível para este item de recorte",
};
